services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://username:password@postgres:5432/simple_bank?sslmode=disable
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
